version: '3'

vars:
  MANAGE_PY: python ./cctv_api/manage.py
tasks:

  default:
    silent: true
    desc: Show help
    cmds:
      - task --list

  clean:
    desc: Clean up temporary files
    cmds:
      - rm -rf .venv

  startdevserver:
    desc: Start Django test server
    cmds:
      - uv run {{.MANAGE_PY}} runserver

  migrate:
    desc: Run Django migrations
    cmds:
      - uv run {{.MANAGE_PY}} migrate

  makemigrations:
    desc: Create Django migrations
    cmds:
      - uv run {{.MANAGE_PY}} makemigrations

  add-csv:*:
    vars:
      CSV_FILE: "{{index .MATCH 0}}"
    desc: Process CSV data file. task process-csv-data:<path-to-csv-file>
    cmds:
      - uv run {{.MANAGE_PY}} add_csv_file {{.CSV_FILE}}

  collectstatic:
    desc: Collect static files
    cmds:
      - uv run {{.MANAGE_PY}} collectstatic --noinput

  fmt:
    desc: Format code
    cmds:
      - uv format --preview-features format
  
  startserver:
    desc: Start production server
    dir: ./cctv_api
    deps:
      - clean
      - collectstatic
      - migrate
    cmds:
      - uv run uvicorn cctv_core.asgi:application --host 0.0.0.0 --port 8000
      
  syncdata:
    desc: Sync data from external excels to database
    cmds:
      - uv run {{.MANAGE_PY}} sync_cameras
      - uv run {{.MANAGE_PY}} sync_record_filter

  healthcheck:
    desc: Check if the server is healthy
    silent: true
    cmds:
      - bash -c "exec 6<>/dev/tcp/localhost/8000" && echo "Server is healthy" || (echo -n "Server is not healthy" && exit 1)