# Generated by Django 4.2.7 on 2025-10-30 16:39

import cctv_records.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraGroups",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("name", models.TextField(help_text="Name of the Group", unique=True)),
                ("description", models.TextField(default="no-description")),
            ],
            options={
                "verbose_name_plural": "Camera Groups",
                "db_table": "camera_groups",
            },
        ),
        migrations.CreateModel(
            name="CameraRecordsFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("number_of_records", models.TextField()),
                ("number_of_cameras", models.TextField()),
                ("filename", models.TextField(unique=True)),
                ("file", models.FileField(upload_to="")),
                ("earliest_record_datetime", models.DateTimeField()),
                ("latest_record_datetime", models.DateTimeField()),
                ("number_of_downloads", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Camera Records Files",
                "get_latest_by": "uploaded",
            },
        ),
        migrations.CreateModel(
            name="Cameras",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "camera_id",
                    cctv_records.models.LowerTextField(
                        help_text="Camera reference code (don't publish). Lowercase only.", unique=True
                    ),
                ),
                ("label", models.TextField(help_text="Description/Label of Camera")),
                ("longitude", models.FloatField(help_text="Camera Location longitude (EPSG:4326)", null=True)),
                ("latitude", models.FloatField(help_text="Camera Location latitude (EPSG:4326)", null=True)),
                ("is_complete", models.BooleanField(default=False, help_text="Is the camera data complete?")),
                ("groups", models.ManyToManyField(related_name="cameras", to="cctv_records.cameragroups")),
            ],
            options={
                "verbose_name_plural": "Cameras",
                "db_table": "camera_cameras",
                "ordering": ["camera_id"],
            },
        ),
        migrations.CreateModel(
            name="YOLORecords",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(help_text="Datetime of the capture.")),
                (
                    "camera_ok",
                    models.BooleanField(
                        choices=[("None", "Unknown"), ("True", "True"), ("False", "False")],
                        default="None",
                        help_text="A T/F/Null flag if the camera was operating normally the time of capture. null values mean it was unknown. ",
                        null=True,
                    ),
                ),
                ("model_name", models.TextField(default="yolo", editable=False, help_text="Model Name")),
                ("cars", models.IntegerField(default=0, help_text="Number of cars")),
                ("pedestrians", models.IntegerField(default=0, help_text="Number of pedestrians")),
                ("cyclists", models.IntegerField(default=0, help_text="Number of cyclists")),
                ("motorcycles", models.IntegerField(default=0, help_text="Number of motorcycles")),
                ("buses", models.IntegerField(default=0, help_text="Number of buses")),
                ("lorries", models.IntegerField(default=0, help_text="Number of lorries")),
                ("vans", models.IntegerField(default=0, help_text="Number of vans")),
                ("taxis", models.IntegerField(default=0, help_text="Number of taxis")),
                (
                    "camera",
                    models.ForeignKey(
                        help_text="Camera Location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_cameras",
                        related_query_name="%(app_label)s_%(class)s_cameras",
                        to="cctv_records.cameras",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "YOLORecords",
                "db_table": "yolo_records",
                "ordering": ("-timestamp", "camera"),
            },
        ),
        migrations.CreateModel(
            name="TF2Records",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(help_text="Datetime of the capture.")),
                (
                    "camera_ok",
                    models.BooleanField(
                        choices=[("None", "Unknown"), ("True", "True"), ("False", "False")],
                        default="None",
                        help_text="A T/F/Null flag if the camera was operating normally the time of capture. null values mean it was unknown. ",
                        null=True,
                    ),
                ),
                ("cars", models.IntegerField(default=None, help_text="Number of cars")),
                ("persons", models.IntegerField(default=None, help_text="Number of persons.")),
                ("bicycles", models.IntegerField(default=None, help_text="Number of bicycles.")),
                ("trucks", models.IntegerField(default=None, help_text="Number of trucks.")),
                ("motorcycles", models.IntegerField(default=None, help_text="Number of motorcycles.")),
                ("buses", models.IntegerField(default=None, help_text="Number of busses.")),
                ("model_name", models.TextField(default="tf2", editable=False, help_text="Model Name")),
                (
                    "camera",
                    models.ForeignKey(
                        help_text="Camera Location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_cameras",
                        related_query_name="%(app_label)s_%(class)s_cameras",
                        to="cctv_records.cameras",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TF2Records",
                "db_table": "tf2_records",
                "ordering": ("-timestamp", "camera"),
            },
        ),
        migrations.CreateModel(
            name="TF1Records",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(help_text="Datetime of the capture.")),
                (
                    "camera_ok",
                    models.BooleanField(
                        choices=[("None", "Unknown"), ("True", "True"), ("False", "False")],
                        default="None",
                        help_text="A T/F/Null flag if the camera was operating normally the time of capture. null values mean it was unknown. ",
                        null=True,
                    ),
                ),
                ("cars", models.IntegerField(default=None, help_text="Number of cars")),
                ("persons", models.IntegerField(default=None, help_text="Number of persons.")),
                ("bicycles", models.IntegerField(default=None, help_text="Number of bicycles.")),
                ("trucks", models.IntegerField(default=None, help_text="Number of trucks.")),
                ("motorcycles", models.IntegerField(default=None, help_text="Number of motorcycles.")),
                ("buses", models.IntegerField(default=None, help_text="Number of buses.")),
                ("model_name", models.TextField(default="tf1", editable=False)),
                (
                    "camera",
                    models.ForeignKey(
                        help_text="Camera Location",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_cameras",
                        related_query_name="%(app_label)s_%(class)s_cameras",
                        to="cctv_records.cameras",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TF1Records",
                "db_table": "tf1_records",
                "ordering": ("-timestamp", "camera"),
            },
        ),
        migrations.CreateModel(
            name="RecordsFilter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "model",
                    models.CharField(
                        choices=[("tf1", "TF1"), ("tf2", "TF2"), ("yolo", "YOLO")], default="yolo", max_length=10
                    ),
                ),
                ("from_datetime", models.DateTimeField()),
                ("to_datetime", models.DateTimeField()),
                ("camera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cctv_records.cameras")),
            ],
        ),
        migrations.AddConstraint(
            model_name="yolorecords",
            constraint=models.UniqueConstraint(fields=("timestamp", "camera"), name="yolo_unique_timestamp_camera"),
        ),
        migrations.AddConstraint(
            model_name="tf2records",
            constraint=models.UniqueConstraint(fields=("timestamp", "camera"), name="tf2_unique_timestamp_camera"),
        ),
        migrations.AddConstraint(
            model_name="tf1records",
            constraint=models.UniqueConstraint(fields=("timestamp", "camera"), name="tf1_unique_timestamp_camera"),
        ),
    ]
