# Generated by Django 4.2.25 on 2025-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cctv_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tf1records",
            name="bicycles",
            field=models.IntegerField(default=None, help_text="Number of bicycles.", null=True),
        ),
        migrations.AlterField(
            model_name="tf1records",
            name="buses",
            field=models.IntegerField(default=None, help_text="Number of buses.", null=True),
        ),
        migrations.AlterField(
            model_name="tf1records",
            name="camera_ok",
            field=models.BooleanField(
                choices=[("None", "Unknown"), ("True", "True"), ("False", "False")],
                help_text="A T/F/Null flag if the camera was operating normally the time of capture. null values mean it was unknown. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tf1records",
            name="cars",
            field=models.IntegerField(default=None, help_text="Number of cars", null=True),
        ),
        migrations.AlterField(
            model_name="tf1records",
            name="motorcycles",
            field=models.IntegerField(default=None, help_text="Number of motorcycles.", null=True),
        ),
        migrations.AlterField(
            model_name="tf1records",
            name="persons",
            field=models.IntegerField(default=None, help_text="Number of persons.", null=True),
        ),
        migrations.AlterField(
            model_name="tf1records",
            name="trucks",
            field=models.IntegerField(default=None, help_text="Number of trucks.", null=True),
        ),
        migrations.AlterField(
            model_name="tf2records",
            name="bicycles",
            field=models.IntegerField(default=None, help_text="Number of bicycles.", null=True),
        ),
        migrations.AlterField(
            model_name="tf2records",
            name="buses",
            field=models.IntegerField(default=None, help_text="Number of busses.", null=True),
        ),
        migrations.AlterField(
            model_name="tf2records",
            name="camera_ok",
            field=models.BooleanField(
                choices=[("None", "Unknown"), ("True", "True"), ("False", "False")],
                help_text="A T/F/Null flag if the camera was operating normally the time of capture. null values mean it was unknown. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tf2records",
            name="cars",
            field=models.IntegerField(default=None, help_text="Number of cars", null=True),
        ),
        migrations.AlterField(
            model_name="tf2records",
            name="motorcycles",
            field=models.IntegerField(default=None, help_text="Number of motorcycles.", null=True),
        ),
        migrations.AlterField(
            model_name="tf2records",
            name="persons",
            field=models.IntegerField(default=None, help_text="Number of persons.", null=True),
        ),
        migrations.AlterField(
            model_name="tf2records",
            name="trucks",
            field=models.IntegerField(default=None, help_text="Number of trucks.", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="buses",
            field=models.IntegerField(default=None, help_text="Number of buses", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="camera_ok",
            field=models.BooleanField(
                choices=[("None", "Unknown"), ("True", "True"), ("False", "False")],
                help_text="A T/F/Null flag if the camera was operating normally the time of capture. null values mean it was unknown. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="cars",
            field=models.IntegerField(default=None, help_text="Number of cars", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="cyclists",
            field=models.IntegerField(default=None, help_text="Number of cyclists", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="lorries",
            field=models.IntegerField(default=None, help_text="Number of lorries", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="motorcycles",
            field=models.IntegerField(default=None, help_text="Number of motorcycles", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="pedestrians",
            field=models.IntegerField(default=None, help_text="Number of pedestrians", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="taxis",
            field=models.IntegerField(default=None, help_text="Number of taxis", null=True),
        ),
        migrations.AlterField(
            model_name="yolorecords",
            name="vans",
            field=models.IntegerField(default=None, help_text="Number of vans", null=True),
        ),
    ]
