# Generated by Django 4.2.25 on 2025-11-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv_records', '0002_alter_tf1records_bicycles_alter_tf1records_buses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameras',
            name='groups',
        ),
        migrations.DeleteModel(
            name='CameraGroups',
        ),
    ]
