# Generated by Django 4.2.25 on 2025-11-11 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cctv_records", "0003_remove_cameras_groups_delete_cameragroups"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CameraRecordsFile",
        ),
    ]
