# Generated by Django 4.2.25 on 2025-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cctv_records", "0004_delete_camerarecordsfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsfilter",
            name="model",
            field=models.CharField(choices=[("tf2", "TF2"), ("yolo", "YOLO")], default="yolo", max_length=10),
        ),
        migrations.DeleteModel(
            name="TF1Records",
        ),
    ]
